theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag
title: "katelibby.chat - a chat bot for slack and discord"
tagline: "katelibby is for running fun commands directly into slack and discord."
description: "A Bot created by wh.iterabb.it to bring information and fun into slack and discord chats. Please chat responsibly."
image: 
  path: /assets/images/katelogo.png
  height: 128
  width: 128
  alt: Kate Libby Logo
social:
  name: Kate Libby
  links:
    - https://github.com/wh-iterabb-it/
    - https://wh.iterabb.it/
    - https://defcon.social/@kate
url: katelibby.chat
